# Generated by Django 4.2 on 2024-08-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('R', 'Rock'), ('E', 'Electronica'), ('C', 'Clasica'), ('B', 'Bossa Nova'), ('H', 'Hip-Hop')], max_length=30)),
                ('year', models.IntegerField(default=2000)),
                ('picture', models.ImageField(upload_to='pokemons_images')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
