# Generated by Django 4.2 on 2024-08-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album_manager.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('C', 'Clasica'), ('R', 'Rock'), ('B', 'Bossa Nova'), ('H', 'Hip-Hop'), ('E', 'Electronica')], max_length=30),
        ),
    ]
