# Generated by Django 4.2 on 2024-08-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0002_album_artist_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('C', 'Clasica'), ('H', 'Hip-Hop'), ('E', 'Electronica'), ('B', 'Bossa Nova'), ('R', 'Rock')], max_length=30),
        ),
    ]
