# Generated by Django 4.2 on 2024-08-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_manager', '0003_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('B', 'Bossa Nova'), ('H', 'Hip-Hop'), ('C', 'Clasica'), ('R', 'Rock'), ('E', 'Electronica')], max_length=30),
        ),
    ]
